# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 7.35.0
"""gRPC Agent 服务的 protobuf 生成的 Python 消息定义。

由 protoc 自动生成，包含 TaskRequest、TaskResponse、HealthRequest、HealthResponse、
CapabilitiesRequest、CapabilitiesResponse 等消息类。
请勿手动修改此文件；如需调整数据结构，请修改对应的 .proto 源文件并重新生成。
"""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x08solagent\"i\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x14\n\x0ctarget_agent\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x04 \x01(\x01\x12\x10\n\x08priority\x18\x05 \x01(\x05\"c\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x05\"\x0f\n\rHealthRequest\"R\n\x0eHealthResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x11\n\tlast_seen\x18\x03 \x01(\x01\x12\x0c\n\x04load\x18\x04 \x01(\x01\"\x15\n\x13\x43\x61pabilitiesRequest\"g\n\x14\x43\x61pabilitiesResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05modes\x18\x02 \x03(\t\x12\r\n\x05tools\x18\x03 \x03(\t\x12\x0e\n\x06models\x18\x04 \x03(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t2\xd4\x01\n\x0c\x41gentService\x12\x38\n\x07\x45xecute\x12\x15.solagent.TaskRequest\x1a\x16.solagent.TaskResponse\x12;\n\x06Health\x12\x17.solagent.HealthRequest\x1a\x18.solagent.HealthResponse\x12M\n\x0c\x43\x61pabilities\x12\x1d.solagent.CapabilitiesRequest\x1a\x1e.solagent.CapabilitiesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=25
  _globals['_TASKREQUEST']._serialized_end=130
  _globals['_TASKRESPONSE']._serialized_start=132
  _globals['_TASKRESPONSE']._serialized_end=231
  _globals['_HEALTHREQUEST']._serialized_start=233
  _globals['_HEALTHREQUEST']._serialized_end=248
  _globals['_HEALTHRESPONSE']._serialized_start=250
  _globals['_HEALTHRESPONSE']._serialized_end=332
  _globals['_CAPABILITIESREQUEST']._serialized_start=334
  _globals['_CAPABILITIESREQUEST']._serialized_end=355
  _globals['_CAPABILITIESRESPONSE']._serialized_start=357
  _globals['_CAPABILITIESRESPONSE']._serialized_end=460
  _globals['_AGENTSERVICE']._serialized_start=463
  _globals['_AGENTSERVICE']._serialized_end=675
# @@protoc_insertion_point(module_scope)
