"""Memory provider protocol. Reference: hermes-agent MemoryProvider, crewAI Memory abstract class."""
from typing import Protocol, runtime_checkable

from solagent.schema.memory import MemoryQuery, MemoryRecord, MemorySearchResult


@runtime_checkable
class MemoryProvider(Protocol):
    async def add(self, record: MemoryRecord) -> None: ...
    async def search(self, query: MemoryQuery) -> list[MemorySearchResult]: ...
    async def get(self, memory_id: str) -> MemoryRecord | None: ...
    async def delete(self, memory_id: str) -> bool: ...
    async def clear(self) -> None: ...
    async def system_prompt_block(self) -> str: ...